### ISSUE TITLE
Please add AN179 In-Wall On/Off module

### ISSUE THREAD

**Issue by MbenzNo** [ralfvd/com.everspring#16]
I have several AN179 In-Wall On/Off modules that is not correctly identified by Homey.
Mine is branded "Smart Home Europe", but it seems that the same device is also branded Everspring AN179 and Nexa AN179. 
Manual for mine: https://detintelligentehjem.dk/amfile/file/download/file_id/41/product_id/319/

It includes as an Unknown device and it is possible to control it as an On/Off switch.

Node information:
Node ID: 48
Secure: No
Battery: No
Manufacturer ID: 96
Product Type ID: 4
Product ID: 8
Device Class (Basic): Basic_Type_Routing_Slave
Device Class (Generic): Generic_Type_Switch_Binary
Device Class (Spesific): Spesific_Type_Power_Switch_Binary

**Comment by ralfvd** [comment]
Code for the AN179 is now available on GitHub, but I cannot test it myself , since I don't have the device at hand.  Please use the GitHub code and the Athom Cli to install and check.

**Comment by MbenzNo** [comment]
Thank You. I am not at home before Next Friday, so it have to wait until then before I give it a try.

St1-R.

Sendt fra E-post for Windows 10

Fra: ralfvd
Sendt: mandag 5. juni 2017 kl. 22.21
Til: ralfvd/com.everspring
Kopi: MbenzNo; Author
Emne: Re: [ralfvd/com.everspring] Please add AN179 In-Wall On/Off module(#16)

Code for the AN179 is now available on GitHub, but I cannot test it myself , since I don't have the device at hand. Please use the GitHub code and the Athom Cli to install and check.

**Comment by MbenzNo** [comment]
Ok. I am home again, but i have to learn how to use the code and use Athom Cli...
St.by while I am Googling...

**Comment by MbenzNo** [comment]
I have uninstalled v 0.2.1 and CLI installed v 0.2.2

Sadly, the app crashes immediately and I have not been able to do any further testing.

St1-R.


Sendt fra E-post for Windows 10

Fra: ralfvd
Sendt: mandag 5. juni 2017 kl. 22.21
Til: ralfvd/com.everspring
Kopi: MbenzNo; Author
Emne: Re: [ralfvd/com.everspring] Please add AN179 In-Wall On/Off module(#16)

Code for the AN179 is now available on GitHub, but I cannot test it myself , since I don't have the device at hand. Please use the GitHub code and the Athom Cli to install and check.

**Comment by ralfvd** [comment]
Can you send me an email to ralfvd@gmail.com ; then we can troubleshoot
together and I might be able to provide an easier way to test the app.

Ralf

On 12 Jun 2017 at 16:08:24, MbenzNo (notifications@github.com) wrote:

I have uninstalled v 0.2.1 and CLI installed v 0.2.2

Sadly, the app crashes immediately and I have not been able to do any
further testing.

St1-R.


Sendt fra E-post for Windows 10

Fra: ralfvd
Sendt: mandag 5. juni 2017 kl. 22.21
Til: ralfvd/com.everspring
Kopi: MbenzNo; Author
Emne: Re: [ralfvd/com.everspring] Please add AN179 In-Wall On/Off
module(#16)

Code for the AN179 is now available on GitHub, but I cannot test it myself
, since I don't have the device at hand. Please use the GitHub code and the
Athom Cli to install and check.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ralfvd/com.everspring/issues/16#issuecomment-307800271>,
or mute the thread
