### ISSUE TITLE
AD147 settings don't seem to work

### ISSUE THREAD

**Issue by roelvdberge** [ralfvd/com.everspring#6]
First of all: thanks for your hard work! It was a delight to see support for the Everspring AD147 dimmers!

But I do have an issue with it. Whenever it turns on, the luminance will always be set to 100%. I changed the settings and they have no effect. In the flows I try to set the luminance (instead of turning on), but here as well the luminance is set to 100%. Could this be solved? If I can be of assistance in any way, please don't hesitate to contact me!

With kind regards,

Roel van den Berge

**Comment by posthok** [comment]
I've got almost the same issue with AD147.
In devices the luminance is manualy changeble from 1 to 100%.
But doing the same in a flow nothing happens.

**Comment by ralfvd** [comment]
Under investigation

**Comment by posthok** [comment]
Also in firmware version 1.05 it's not possible to dim the AD147. When set a dim for example 50% from a flow the light goes alway to 100%. Set it to 50% from the device it works normal.
App version 1.0.10

**Comment by posthok** [comment]
Is there any progress to get this device to work?

**Comment by ralfvd** [comment]
I though I mentioned it before, but at least not in this reported issue: this is an issue with the Homey firmware. What actually happens when you set a dim in a flow is this:

'set dim 0.50' 
'set onoff true' -> and this is then translated into 'set dim 0.99'. 

When executing a dim command from the device card, only the 'set dim 0.50' is sent. 

I cannot prevent this from happening from inside the app; This is documented in issue https://github.com/athombv/homey/issues/934

I tried to think of some workarounds to make it work, but the issue is the 'onoff true' command that is sent after the dim command. 

The Homey firmware needs to change this flow behaviour equal to the behaviour in the device card.

**Comment by posthok** [comment]
I Hope Athom is also aware of this problem so they can take appropriate actions

**Comment by ralfvd** [comment]
Please see the communication in the athombv/homey#934 issue. They are aware of the problem, and changes are coming but unknown when and how. This issue has been open for a while now.

**Comment by posthok** [comment]
Strange thing is that a recently bought (As a replacement for the everspring) tkb socket dimmer is working fine.

**Comment by ralfvd** [comment]
@posthok I've re-investigated today and although it is still a bug within the Homey FW, I found a workaround which seems to work.  It will be in version 0.1.5 which is pending in the app store for approval right now. 

If you can install locallly, you can download it from GitHub and test it.

**Comment by posthok** [comment]
Thanx will do that.

**Comment by roelvdberge** [comment]
Just installed version 0.1.6 and it indeed solved this issue.
Thank you very much for your work, it is highly appreciated!

Cheers, Roel
