### ISSUE TITLE
Crash after setting property of AD1422

### ISSUE THREAD

**Issue by sossienl** [ralfvd/com.everspring#7]
When setting the checkbox for my AD1422 EVERSPRING Wall Plug that 'switches' between dim and on/off, the app crashes and the device is unresponsive.

Also it seems like Homey is not always reflecting the correct current state.

Stack trace:

TypeError: Cannot read property 'CONFIGURATION_SET' of undefined
at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:177:63
at Array.forEach (native)
at ZwaveDriver.settings (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:136:18)
at /homey-app/manager/drivers.js:207:21
at ZwaveDriver.drivers.(anonymous function).ready (/homey-app/manager/drivers.js:131:9)
at eventListeners.clientDriverMessage (/homey-app/manager/drivers.js:170:10)
at /homey-app/manager/drivers.js:26:41
at Object.Homey.ready (/homey-app/homey.js:1:1008)
at /homey-app/manager/drivers.js:25:11
at /homey-app/helpers/client.js:1:1077

Exit code: 1
Exit signal: null

**Comment by ralfvd** [comment]
An AD1422 is on its way for investigation of this issue

**Comment by ralfvd** [comment]
The AD142(2) doesn't have any configuration settings possible. There are non in the manual, and when pairing the device, it doesn't state that is has a possibility for configuration settings. So that is causing the crash when trying to adjust the properties. 

In an upcoming release, I've deleted the configuration settings. But you will need to re-pair (or just don't alter the configuration settings). 

Can you detail more on the 'not reflecting the correct state' ?  Do you mean that your light is on, but the card states it is off? I can reproduce that by turning the light off, then sliding the dimmer to e.g. 50 % on the device card. The light will go on, but Homey will state the light is off.

Or when I manually press the button on the socket, it will turn on/off, but this is not reflected in Homey's device card.

Is that what you mean?

**Comment by ralfvd** [comment]
@sossienl  do you still see any issues?
